# -*- coding: utf-8 -*-
"""Armstrong.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ruTbL3FHoE0hMgxxWL-iyMxzNn7Ydmwz
"""

num=int(input("Enter a number: "))
a=num
s=0
while num>0:
  rem=num%10
  c=rem*rem*rem     #rem**3
  s=s+c
  num//=10
if s==a:
  print("Armstrong")
else:
  print("Not an Armstrong")