# -*- coding: utf-8 -*-
"""Factorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KcXe7HJn_SFaJx6lpkEqWEvM9BwFMYPZ
"""

f=1
a=int(input("Enter a number: "))
if a==0:
  print("Factorial is 1")
else:
  for i in range(1,a+1):
    f=f*i
  print("Factorial is ",f)