# -*- coding: utf-8 -*-
"""Fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16U8OArNz1zpJkuTV07tMwYY-m_tLuCuJ
"""

n1=0 
n2=1
a=int(input("Enter the limit: "))
print(n1,n2,end=" ")
for i in range(1,a+1):
  n3=n1+n2
  n1=n2
  n2=n3
  print(n3,end=" ")