# -*- coding: utf-8 -*-
"""Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18zC_9jbwXjtO_UbdD-CB2zrajbTK8lnh
"""

#Call by Value

def call(string):
  string="RUTUJA"
  print("Inside: ",string)
string="rutuja"
call(string)
print("Outside: ",string)

def call(set1):
  set1.add(40)
  print("Inside: ",set1)
set1={10,20,30}
call(set1)
print("Outside: ",set1)