# -*- coding: utf-8 -*-
"""Matrix_Multiplication.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B5FIH2ZYELv0LUvho8pLqyxOEHurM0OI
"""

import numpy as np
a=np.array([[1,2,3],[3,6,4],[5,8,9]])
b=np.array([[6,12,13],[3,9,14],[5,1,2]])
c=np.dot(a,b)
print(c)