# -*- coding: utf-8 -*-
"""Pattern.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mVZLDVVGYewkdAtTX-Srn3vEFhLMhjJX
"""

for i in range(6):
  for j in range(i):
    print("*",end=' ')
  print("")