# -*- coding: utf-8 -*-
"""Prime.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ab34j8hk8PJ6--Yyg0kZ6D0a9zeWahST
"""

flag=0;
num=int(input("Enter a number: "))
for i in range(2,num):
  if num%2==0:
    flag=1
    break
  else:
    flag=0
if(flag):
  print("Not a Prime number")
else:  
  print("Prime number")