# -*- coding: utf-8 -*-
"""Swap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CTT8JLOQWPf4ujHZthkLfaD7URIjuWwI
"""

print("Before Swapping")
a=int(input("Enter first number: "))
b=int(input("Enter second number: "))
temp=a
a=b
b=temp
print("After Swapping")
print("First number: ",a)
print("Second number: ",b)